import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import styles from '../styles/Home.module.css'
import requests from '../utils/requests'
import { GetServerSideProps } from 'next'


export default function Home({results}) {

  console.log(results)


  return (
    <div className={styles.container}>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        
      
      {/*Header*/}
      <Header />

      {/*Navigation*/}
      <Nav />

      

      <Results requests={results}/>
</div> 


      
  )
}

export async function getServerSideProps(context){

  const genre = context.query.genre 




  //const request = await fetch(`https://api.themoviedb.org/3/movie/550${requests['fetchActionMovies']?.url || requests.fetchTrending.url}`


  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`
  ).then(res => res.json())

  

  return { props: { results: request.results}}
}
